# Generated by Django 2.2 on 2019-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190503_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='end_week',
        ),
        migrations.RemoveField(
            model_name='member',
            name='start_week',
        ),
        migrations.RemoveField(
            model_name='member',
            name='series',
        ),
        migrations.AddField(
            model_name='member',
            name='series',
            field=models.ManyToManyField(related_name='members', through='api.Residency', to='api.Series'),
        ),
    ]
